### ISSUE TITLE
Errors do not display the faulty line of code correctly

### ISSUE THREAD

**Issue by PaukkuPalikka** [JiftDev/jift-compiler-test#1]
`test/input.jift`:
```
0b
```
When running with `./build run test/input.jift`:
```
Error:
2 | b
~~~~~~^
expected a binary digit after `0b`
```
displays `2 | b` instead of the actual line `0b`
Btw maybe you could switch to using a Makefile :}

**Comment by EEVV** [comment]
Fixed in the current commit `d1bc857408c2725d9761ed99c53a5e81e2ebe6ad` of the `devel` branch.
